# Question no 1 answer

In [13]:
import numpy as np
arr=np.arange(2,51,3)
print(arr)


[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Question no 2 answer

In [9]:
import numpy as np
list1=[]
list2=[]
for i in range(5) :
    a=int(input())
    list1.append(a) 
print(list1)
print()
for i in range(5) :
    b=int(input())
    list2.append(b)
print(list2)
arr1=np.array(list1)
arr2=np.array(list2)
print()
print(arr1)
print()
print(arr2)
print()
arr=np.concatenate((arr1,arr2))
print(arr)
print(np.sort(arr))

2
3
1
5
4
[2, 3, 1, 5, 4]

7
6
9
10
8
[7, 6, 9, 10, 8]

[2 3 1 5 4]

[ 7  6  9 10  8]

[ 2  3  1  5  4  7  6  9 10  8]
[ 1  2  3  4  5  6  7  8  9 10]


# Question no 3 answer

In [14]:
import numpy as np
arr_1d=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr_1d)
print()
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr_2d)
print()
print(arr_1d.ndim)
print()
print(arr_2d.ndim)
print()
print(arr_1d.shape)
print()
print(arr_2d.shape)
print()
print(arr_1d.size)
print()
print(arr_2d.size)

[ 1  2  3  4  5  6  7  8  9 10]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

1

2

(10,)

(4, 3)

10

12


# Question no 4 answer

In [24]:
import numpy as np
arr=np.arange(10)
print(arr)
print()
print(arr.shape)
print()
arr1=arr[np.newaxis,:]
print(arr1)
print()
print(arr1.shape)

[0 1 2 3 4 5 6 7 8 9]

(10,)

[[0 1 2 3 4 5 6 7 8 9]]

(1, 10)


In [25]:
import numpy as np
arr=np.arange(10)
print(arr)
print()
print(arr.shape)
print()
arr1=np.expand_dims(arr, axis=1)
print(arr1)
print()
print(arr1.shape)

[0 1 2 3 4 5 6 7 8 9]

(10,)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

(10, 1)


In [26]:
import numpy as np
arr=np.arange(10)
print(arr)
print()
print(arr.shape)
print()
arr1=np.expand_dims(arr, axis=0)
print(arr1)
print()
print(arr1.shape)

[0 1 2 3 4 5 6 7 8 9]

(10,)

[[0 1 2 3 4 5 6 7 8 9]]

(1, 10)


# Question no 5 answer

In [30]:
import numpy as np
arr1=np.array([2,6,8,10])
arr2=np.array([1,15,18,36])
a=np.square(arr1)
b=np.square(arr2)
print(a)
print()
print(b)
print()
print(np.vstack((a,b)))
print()
print(np.hstack((a,b)))

[  4  36  64 100]

[   1  225  324 1296]

[[   4   36   64  100]
 [   1  225  324 1296]]

[   4   36   64  100    1  225  324 1296]


# Question no 6 answer

In [33]:
import numpy as np

arr = np.array([1,1,1,2,2,2,5,25,1,1])
unique, counts = np.unique(arr, return_counts=True)

print(np.asarray((unique, counts)).T)

[[ 1  5]
 [ 2  3]
 [ 5  1]
 [25  1]]
